default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: content-indexer_development

test:
  <<: *default
  database: content-indexer_test

production:
  <<: *default
  database: content-indexer_production
  username: content-indexer
  password: <%= ENV['CONTENT-INDEXER-DATABASE_PASSWORD'] %>
